version: '2'
services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tgchatbot
      - POSTGRES_USER=tgchatbot
      - POSTGRES_PASSWORD=tgchatbot
    ports:
      - "5432:5432"
  bot:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local